# Generated by Django 5.2.10 on 2026-02-21 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_sample'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
    ]
