# Generated by Django 5.2.10 on 2026-02-23 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_song_album_delete_album_delete_song'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
    ]
